name: CI

on: [push, pull_request]

env:
  CXX: g++

jobs:
  build:
    name: Build & test
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: 6.4.*

      - name: Install build dependencies
        run: sudo apt-get install -y ninja-build

      - name: Check format
        run: clang-format -n -Werror src/**/*.cpp src/**/*.hpp tests/**/*.cpp

      - name: Cache build output
        id: cache-build
        uses: actions/cache@v3
        with:
          path: build
          key: ${{ runner.os }}-build

      - name: Configure build
        run: |
          cmake -Bbuild -S . \
                -DCMAKE_BUILD_TYPE=Debug \
                -DQMODSORTER_BUILD_TESTS=ON \
                -G Ninja

      - name: Build
        run: cd build && ninja -j2

      - name: Run tests
        env:
          CTEST_OUTPUT_ON_FAILURE: 1
        run: cd build/tests && ctest -C ${{matrix.build_type}} -j 2
